In [5]:
import pandas as pd 
import numpy as np

In [6]:
from sklearn.impute import SimpleImputer #Missing values are filled unlike transditional method to fill mean median mode
from sklearn.preprocessing import OneHotEncoder #if we have data having no order like male/female then it assigns encode pd.get dummies
from sklearn.preprocessing import OrdinalEncoder #determine categories in categorical data i.e. ordinal or not its gives 0 or 1 if good 

In [38]:
df = pd.read_csv('data/covid_toy.csv')
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [9]:
df.shape

(100, 6)

In [10]:
df.city.unique()

array(['Kolkata', 'Delhi', 'Mumbai', 'Bangalore'], dtype=object)

In [20]:
df.gender.unique()

array(['Male', 'Female'], dtype=object)

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [22]:
X_train

,age,gender,fever,cough,city
22,71,Female,98.0,Strong,Kolkata
35,82,Female,102.0,Strong,Bangalore
37,55,Male,100.0,Mild,Kolkata
47,18,Female,104.0,Mild,Bangalore
91,38,Male,NaN,Mild,Delhi
...,...,...,...,...,...
4,65,Female,101.0,Mild,Mumbai
30,15,Male,101.0,Mild,Delhi
11,65,Female,98.0,Mild,Mumbai
42,27,Male,100.0,Mild,Delhi


In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [19]:
X_train

,age,gender,fever,cough,city
33,26,Female,98.0,Mild,Kolkata
61,81,Female,98.0,Strong,Mumbai
23,80,Female,98.0,Mild,Delhi
35,82,Female,102.0,Strong,Bangalore
30,15,Male,101.0,Mild,Delhi
...,...,...,...,...,...
11,65,Female,98.0,Mild,Mumbai
2,42,Male,101.0,Mild,Delhi
68,54,Female,104.0,Strong,Kolkata
55,81,Female,101.0,Mild,Mumbai


In [23]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [24]:
X_train_fever

array([[ 98.        ],
       [102.        ],
       [100.        ],
       [104.        ],
       [100.73972603],
       [ 98.        ],
       [ 98.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [ 99.        ],
       [101.        ],
       [102.        ],
       [101.        ],
       [100.73972603],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [100.        ],
       [ 99.        ],
       [100.        ],
       [100.73972603],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [100.73972603],
       [102.        ],
       [103.        ],
       [ 99.        ],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [103.        ],
       [100

In [25]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [26]:
X_train_cough

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],

In [27]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [28]:
X_train_gender_city

array([[0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],


In [29]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [30]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [31]:
X_train

,age,gender,fever,cough,city
22,71,Female,98.0,Strong,Kolkata
35,82,Female,102.0,Strong,Bangalore
37,55,Male,100.0,Mild,Kolkata
47,18,Female,104.0,Mild,Bangalore
91,38,Male,NaN,Mild,Delhi
...,...,...,...,...,...
4,65,Female,101.0,Mild,Mumbai
30,15,Male,101.0,Mild,Delhi
11,65,Female,98.0,Mild,Mumbai
42,27,Male,100.0,Mild,Delhi


In [32]:
pd.DataFrame(X_train_transformed)

,0,1,2,3,4,5,6
0,71.0,98.000000,0.0,0.0,1.0,0.0,1.0
1,82.0,102.000000,0.0,0.0,0.0,0.0,1.0
2,55.0,100.000000,1.0,0.0,1.0,0.0,0.0
3,18.0,104.000000,0.0,0.0,0.0,0.0,0.0
4,38.0,100.739726,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
75,65.0,101.000000,0.0,0.0,0.0,1.0,0.0
76,15.0,101.000000,1.0,1.0,0.0,0.0,0.0
77,65.0,98.000000,0.0,0.0,0.0,1.0,0.0
78,27.0,100.000000,1.0,1.0,0.0,0.0,0.0


In [33]:
from sklearn.compose import ColumnTransformer

In [34]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(strategy='median'),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [35]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tnf1', SimpleImputer(strategy='median'),
                                 ['fever']),
                                ('tnf2',
                                 OrdinalEncoder(categories=[['Mild',
                                                             'Strong']]),
                                 ['cough']),
                                ('tnf3',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['gender', 'city'])])

In [36]:
transformer.fit_transform(X_train).shape

(80, 7)

In [37]:
transformer.transform(X_test).shape

(20, 7)